### planteamiento del problema
sugerir juegos a nuevos jugadores de nintendo

solo juegos que puedan interesarle

solo 1 juego por mes

In [3]:
import pandas as pd 
data_juegos = pd.read_csv("juegos-ml.csv")
data_juegos

    edad  genero      juegos
0      8       0      accion
1     11       0      accion
2     12       0         fps
3     13       0         fps
4     15       0         fps
5     18       0         fps
6     22       0        jrpg
7     25       0        jrpg
8     28       0        jrpg
9     31       0      accion
10    32       0      accion
11    35       0      accion
12    10       1  plataforma
13    13       1  plataforma
14    14       1  plataforma
15    15       1      puzzle
16    18       1      puzzle
17    19       1         fps
18    22       1         fps
19    25       1         fps

In [4]:
#la ventaja de este set de datos es que no tenemos duplicados, nulos,
#incorrectos ni irrelevantes por lo que no tenemos que limpiarlos
#ahora tenemos que pasarle los datos de entrada(que queremos analizar)
#y salida(los que esperamos)
X = data_juegos.drop(columns=("juegos"))
#el metodo drop quita la columna designada y crea una tabla nueva
X

    edad  genero
0      8       0
1     11       0
2     12       0
3     13       0
4     15       0
5     18       0
6     22       0
7     25       0
8     28       0
9     31       0
10    32       0
11    35       0
12    10       1
13    13       1
14    14       1
15    15       1
16    18       1
17    19       1
18    22       1
19    25       1

In [5]:
#ahora tenemos que obtener el set de datos que queremos tener
#para ello vamos a acceder a una columna en particular
y = data_juegos["juegos"]
y

0         accion
1         accion
2            fps
3            fps
4            fps
5            fps
6           jrpg
7           jrpg
8           jrpg
9         accion
10        accion
11        accion
12    plataforma
13    plataforma
14    plataforma
15        puzzle
16        puzzle
17           fps
18           fps
19           fps
Name: juegos, dtype: object

In [9]:
#vamos a intentar hacer una prediccion con 14 años
from sklearn.tree import DecisionTreeClassifier
modelo = DecisionTreeClassifier()
modelo.fit(X.values, y) #el primero es el modelo base y el segundo es lo esperado
#pero los datos deben de ir sin los nombre de las columnas
predicciones = modelo.predict([[14, 0], [29, 0], [30, 0]])
predicciones

array(['fps', 'jrpg', 'accion'], dtype=object)

In [43]:
#ahora anterirormente le pasamos todos los datos
#pero lo correcto es divirlos en datos de entrenamiento datos
from sklearn.model_selection import train_test_split
##para comparar modelos importamos lo siguiente
from sklearn.metrics import accuracy_score

data_juegos = pd.read_csv("juegos-ml.csv")
X = data_juegos.drop(columns=("juegos"))
y = data_juegos["juegos"]
#agreggamos la variable de entrenamiento
X_entrenar, X_prueba, y_entrenar, y_prueba = train_test_split(X.values, y, test_size=0.2)#aqui le pasamos lo datos base, los de resultado
#y un argumento nombrado con el % de los datos que queremos usar como prueba
#y recibe un numero de 0 a 1 (0.2 es 20%)
#esto nos devulve una tupla, y lo que haremos es desempaquetar esa tupla
#y asignar esos valores a una variable

modelo = DecisionTreeClassifier()
modelo.fit(X_entrenar, y_entrenar)
predicciones = modelo.predict(X_prueba)
predicciones
#ahora lo que tenemos que hacer es comparar los resultados de los modelos
#de prueba con el modelo de prediccion real
puntaje = accuracy_score(y_prueba, predicciones)
puntaje#el valor de abajo va a ir cambiando porque tenemos muy pocos datos
#para aumentar la exactitud podriamos aumentar el % de pruebas

1.0

In [ ]:
#ahora tocaria persistir el modelo, para no tener que probarlo cada
#vez que queramos usarlo y podemas seguir usandolo posteriormente
#para ello tenemos que quitar todo lo de las pruebas y agregar
import joblib
#quitar las predicciones y agregar
joblib.dump(modelo, 'recomendador-juegos.joblib' )#esto va a recibir el modelo, nombre con el que lo
# guardaremos y guardarlo en la ruta que le indiquemos
#despues de guardarlo ya podemos solo cargarlo con
modelo = joblib.load('recomendador-juegos.joblib')
predicciones = modelo.predict([[14, 0]])